# permissions for end users to edit pipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pipeline-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pipeline
    app.kubernetes.io/part-of: pipeline
    app.kubernetes.io/managed-by: kustomize
  name: pipeline-editor-role
rules:
- apiGroups:
  - floo-powder.dev
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - floo-powder.dev
  resources:
  - pipelines/status
  verbs:
  - get
