# permissions for end users to view pipelineruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pipelinerun-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pipeline
    app.kubernetes.io/part-of: pipeline
    app.kubernetes.io/managed-by: kustomize
  name: pipelinerun-viewer-role
rules:
- apiGroups:
  - floo-powder.dev
  resources:
  - pipelineruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - floo-powder.dev
  resources:
  - pipelineruns/status
  verbs:
  - get
