---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - floo-powder.dev
  resources:
  - pipelineruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - floo-powder.dev
  resources:
  - pipelineruns/finalizers
  verbs:
  - update
- apiGroups:
  - floo-powder.dev
  resources:
  - pipelineruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - floo-powder.dev
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - floo-powder.dev
  resources:
  - pipelines/finalizers
  verbs:
  - update
- apiGroups:
  - floo-powder.dev
  resources:
  - pipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - floo-powder.dev
  resources:
  - sources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - floo-powder.dev
  resources:
  - sources/finalizers
  verbs:
  - update
- apiGroups:
  - floo-powder.dev
  resources:
  - sources/status
  verbs:
  - get
  - patch
  - update
