apiVersion: floo-powder.dev/v1alpha1
kind: Source
metadata:
  labels:
    app.kubernetes.io/name: source
    app.kubernetes.io/instance: source-sample
    app.kubernetes.io/part-of: pipeline
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pipeline
  name: source-sample
spec:
  host: "127.0.0.1"
  port: 3306
  plugin: plugin-sample
  config: '{"username":"root","password":"root1234","database":"test","useSSL":true}'
