apiVersion: floo-powder.dev/v1alpha1
kind: Plugin
metadata:
  labels:
    app.kubernetes.io/name: plugin
    app.kubernetes.io/instance: plugin-sample
    app.kubernetes.io/part-of: pipeline
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pipeline
  name: plugin-sample
spec:
  kind: Mysql
  version:
    - "5.6"
    - "5.7"
    - "5.8"
    - "8.0"
  description: "Plugins for reading and writing mysql."
  image: floo-powder/plugin-sample:beta
  config:
    - name: "username"
      kind: "string"
      description: "username for mysql connect"
    - name: "password"
      kind: "password"
      description: "password for mysql connect"
    - name: "database"
      kind: "string"
      description: "database for use"
    - name: "useSSL"
      kind: "bool"
      description: "connect is using ssl?"
