apiVersion: floo-powder.dev/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: pipeline
    app.kubernetes.io/instance: pipeline-sample
    app.kubernetes.io/part-of: pipeline
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pipeline
  name: pipeline-sample
spec:
  # TODO(user): Add fields here
